
- name: stop fucking wildfly
  shell: JAVA_OPTS="-Xmx1024m -Xms512m" ~/wildfly-37.0.1.Final/bin/jboss-cli.sh --connect --controller=localhost:23487 --command="shutdown"
  ignore_errors: yes

- name: start fucking wildfly
  shell: nohup {{ wildfly_dir }}/bin/standalone.sh -Djboss.http.port=23489 -Djboss.https.port=23488 -Djboss.management.http.port=23487 -Djboss.management.https.port=23486 -b 0.0.0.0 -bmanagement 0.0.0.0 -Djboss.thread.pool.max.size=25 >{{log_file}}  2>&1 &

- debug:
    msg: "WildFly restarted!"