ansible_user : s468125
ansible_port : 2222
ansible_python_interpreter : /usr/local/bin/python
ansible_become: false
home: /home/studs/s468125
wildfly_dir: "{{home}}/wildfly-37.0.1.Final"
wildfly_zip: "{{wildfly_dir}}.zip"
log_file: "{{home}}/wildfly.log"
