name: Gelios Server Deploy
run-name: Deploy on gelios using Ansible
on: [push, pull_request]

jobs:
  Deploy on gelios:
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v5
      with:
        playbook: deploy.yml
        directory: ./
        key: ${{secrets.Ansible-ssh-key}}
        inventory: /ansible/inventory.ini
        vault_password: ${{secrets.VAULT_PASSWORD}}
